services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=basic
      - bootstrap.memory_lock=true
      - ES_JAVA_OPT=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1      
    volumes:
      - elastic_data:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 5s
      retries: 120
      start_period: 10s

  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    environment:
      POSTGRES_USER: curator
      POSTGRES_PASSWORD: curator
      POSTGRES_DB: curator
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U curator"]
      interval: 30s
      timeout: 5s
      retries: 120
      start_period: 10s

  qdrant:
    image: qdrant/qdrant:v1.13.4
    container_name: qdrant
    volumes:
      - qdrant_data:/qdrant/storage:rw
    ports:
      - "6334:6334"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 5s
      retries: 120
      start_period: 10s

  redis:
    image: redis:7.4.2-alpine-3.21
    container_name: redis
    volumes:
      - redis_data:/data:rw
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 120
      start_period: 10s

  clip:
    build:
      context: ./clip
      dockerfile: Dockerfile
    container_name: clip
    environment:
      LOG_LEVEL: debug
      GRPC_PORT: 50051
      HEALTH_PORT: 8080
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  elastic_data:
  postgres_data:
  qdrant_data:
  redis_data: